# Generated by Django 3.0.4 on 2021-06-17 08:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_editdraftpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editdraftpage',
            options={'verbose_name': 'Edit Page'},
        ),
        migrations.AddField(
            model_name='editdraftpage',
            name='draft',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
