# Generated by Django 3.0.4 on 2021-06-17 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210617_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editdraftpage',
            name='draft',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='draft',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
