# Generated by Django 3.0.4 on 2021-06-17 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0022_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('coderedcms', '0019_spelling_corrections'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('website', '0005_auto_20210617_0448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditDraftPage',
            new_name='WriteLandingPage',
        ),
        migrations.AlterModelOptions(
            name='writelandingpage',
            options={'verbose_name': 'Write Landing Page'},
        ),
    ]
